blank_issues_enabled: false
contact_links:
  - name: Klipper Forum
    url: https://community.klipper3d.org/
    about: Having an issue? Open a new topic on the Klipper Discourse server.
  - name: Contact Directions
    url: https://www.klipper3d.org/Contact.html
    about: See other Contact information
